name: CI

on: [push]

jobs:
  hello_world_job:
    uses: actions/checkout@v1
    runs-on: ubuntu-latest
    name: A job to say hello
    steps:
    - name: Hello world action step
      id: hello
      uses: sburris/GithubActionHelloWorld@master
      with:
        who-to-greet: 'Sburris'
    # Use the output from the `hello` step
    - name: Get the output time
      run: echo "The time was ${{ steps.hello.outputs.time }}"
